-- 코드를 작성해주세요
SELECT a.ID, c.FISH_NAME, b.LENGTH
FROM FISH_INFO  a
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
    FROM FISH_INFO
    WHERE LENGTH is not null
    GROUP BY FISH_TYPE
) b
ON a.FISH_TYPE = b.FISH_TYPE
AND a.LENGTH = b.LENGTH
JOIN FISH_NAME_INFO  c
ON c.FISH_TYPE = a.FISH_TYPE
ORDER BY a.ID ASC;
